controller:
  kind: DaemonSet
  reportNodeInternalIp: true
  hostPort:
    enabled: true
    ports:
      http: 80
      https: 443
  service:
    type: NodePort
  metrics:
    enabled: true
    podAnnotations:
      prometheus.io/port: "10254"
      prometheus.io/scrape: "true"
    serviceMonitor:
      enabled: "true"
      additionalLabels:
        release: "true"