version: '3.5'

services:
  nginx:
    build:
      context: ./.docker/nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "81:81"
      - "82:82"
      - "83:83"
    depends_on:
      - app-users

  app-users:
    build:
      context: ./.docker/app-users
    container_name: app-users
    environment:
      POSTGRES_HOST: 'service-postgres'
      POSTGRES_DB: 'arch'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres_pass'
    volumes:
      - ./app-users:/app-users

  service-postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_HOST: 'postgres'
      POSTGRES_DB: 'arch'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres_pass'
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    container_name: service-postgres

volumes:
  db-data: