{
 "title": "Метрики ingress contoller",
 "tags": [ "my" ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Latency, ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{namespace=\"default\"}[$__rate_interval])))",
     "legendFormat": "0.5 Квантиль"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{container=\"controller\"}[$__rate_interval])))",
     "legendFormat": "0.95 квантиль"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{container=\"controller\"}[$__rate_interval])))",
     "legendFormat": "0.99 квантиль"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(namespace) (delta(nginx_ingress_controller_requests{namespace=\"default\"}[1m]))",
     "legendFormat": "rps"
    }
   ]
  },
  {
   "title": "RPS ORDERS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(namespace) (delta(nginx_ingress_controller_requests{namespace=\"default\", path=\"/orders(/|$)(.*)\"}[1m]))",
     "legendFormat": "rps"
    }
   ]
  },
  {
   "title": "RPS Billing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(namespace) (delta(nginx_ingress_controller_requests{namespace=\"default\", path=\"/billing(/|$)(.*)\"}[1m]))",
     "legendFormat": "rps"
    }
   ]
  },
  {
   "title": "RPS Products",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(namespace) (delta(nginx_ingress_controller_requests{namespace=\"default\", path=\"/store(/|$)(.*)\"}[1m]))",
     "legendFormat": "rps"
    }
   ]
  },
  {
   "title": "RPS Auth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by(namespace) (delta(nginx_ingress_controller_requests{namespace=\"default\", path=\"/auth\"}[1m]))",
     "legendFormat": "rps"
    }
   ]
  }
 ]
}