appName: app-store

app:
  dbHost: app-store-db-postgresql.kirshov-otus.svc.cluster.local
  dbUser: postgres
  dbPass: postgres_pass
  dbName: store
  redisHost: redis-master.kirshov-otus.svc.cluster.local
  redisPort: 6379
  redisPassword: redis-pass

replicaCount: 1

storeService:
  name: app-store
  image: kirshov/otus-store-service:latest
  port:
    name: app-store-port
    containerPort: 8002
  envFrom:
    - configMapRef:
        name: app-store-env

serviceNginx:
  name: nginx
  image: nginx:latest
  volumeMounts:
    - name: app-store-nginx-config
      mountPath: '/etc/nginx/conf.d'
  portNumber: 80
  portName: nginx

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  name: service-store
  portName: "store-web"

ingress:
  name: ingress-store
  enabled: false
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/auth-url: "http://service-users.kirshov-otus.svc.cluster.local/auth"
    nginx.ingress.kubernetes.io/auth-signin: "http://service-users.kirshov-otus.svc.cluster.local/signin"
    nginx.ingress.kubernetes.io/auth-response-headers: "X-Token"
  hosts:
    - host: otus.project
      paths:
        - path: /store(/|$)(.*)
          pathType: ImplementationSpecific
  tls: []

resources: {}

volumes:
  - name: app-store-nginx-config
    configMap:
      name: app-store-nginx-config

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

configMaps:
  nginxstoreConfigMap: app-store-nginx-config
  storeConfigMap: app-store-env

migrationJob:
  name: store-schema-migration-job
  containers:
    - name: store-schema-update
      image: kirshov/otus-store-service:latest
      command: [ '/bin/sh', '-c', 'php ./vendor/bin/phoenix migrate --config=./src/config/pheonix.php' ]
      envFrom:
        - configMapRef:
            name: app-store-env
  restartPolicy: Never
  backoffLimit: 4