apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.storeService.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.storeService.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.storeService.name }}
    spec:
      containers:
        - name: {{ .Values.storeService.name }}
          image: {{ .Values.storeService.image }}
          imagePullPolicy: Always
          ports:
            - name: {{ .Values.storeService.port.name }}
              containerPort: {{ .Values.storeService.port.containerPort }}
          envFrom:
            {{- toYaml .Values.storeService.envFrom | nindent 12 }}

        - name: {{ .Values.serviceNginx.name }}
          image: {{ .Values.serviceNginx.image }}
          ports:
            - name: {{ .Values.serviceNginx.portName }}
              containerPort: {{ .Values.serviceNginx.portNumber }}
          volumeMounts:
            {{- toYaml .Values.serviceNginx.volumeMounts | nindent 12 }}
      volumes:
        {{- toYaml .Values.volumes | nindent 12 }}