apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: {{ .Values.service.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.appName }}
  ports:
    - protocol: TCP
      port: {{ .Values.serviceNginx.portNumber }}
      targetPort: {{ .Values.serviceNginx.portName }}
      name: {{ .Values.service.portName }}